### PR TITLE
fix: updated timezone-data

### PR DESCRIPTION
**Pull request by JohannesGGE**
Fixes: #287

- Updated timezone-data
- Updated update-zones.py and edited it to work just for updating zones.json

Tested with Mexico_City timezone in Nextcloud and Outlook. Seems to work.

### CODE REVIEW

**Review by miaulalala — APPROVED** [review]
Looks gut, but IANAPD

**Comment by ChristophWurst** [comment]
While at it, let's try to automate this update with a cron workflow similar to https://github.com/nextcloud/server/blob/master/.github/workflows/update-cacert-bundle.yml

**Review by ChristophWurst — COMMENTED** [review]
latitude & longitude is dropped for all zones. is that info no longer provided by the iana data?

**Comment by JohannesGGE** [comment]
Maybe it isn't important for some zones anymore. There are a lot of deletions but also changes and additions.
image
image

**Review by ChristophWurst — APPROVED** [review]

**Review by tcitworld — APPROVED** [review]
As per https://github.com/nextcloud/calendar-js/issues/287#issuecomment-1512556399, we shouldn't use this long-term.

**Pull request merged**
